# Development environment
FROM node:20-alpine

# Create and set working directory
WORKDIR /app

# Copy package.json and yarn.lock
COPY package.json yarn.lock ./

# Install dependencies
RUN yarn install

# Copy prisma schema
COPY prisma/schema.prisma ./prisma/

# Generate Prisma client
RUN yarn prisma generate

# Copy the rest of the application code
COPY . .

# Expose port 8080 for development server
EXPOSE 8080

# Start the development server
CMD ["yarn", "start:dev"]
