export const JWT_ACCESS_SECRET = 'JWT_ACCESS_SECRET';
export const JWT_ACCESS_EXPIRATION = 'JWT_ACCESS_EXPIRATION';
export const JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET';
export const JWT_REFRESH_EXPIRATION = 'JWT_REFRESH_EXPIRATION';
