#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Fix cannot make a commit because of error: "pre-commit: npx: command not found"
# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

yarn lint
